### ISSUE TITLE
r360.compositor.setScreen does not exist for client.js runtime code

### ISSUE THREAD

**Issue by drubio1989** [facebook/react-360#659]
### Description

According to the documentation, in client.js, I can render a video to a flat screen in the following manner:

    r360.compositor.setScreen(
      'default', /* screen name */
      'myplayer', /* player unique id */
      'default', /* surface name */
      0, 0, 600, 400 /* relative position on the surface */
    );

#### Expected behavior

This should set a video on a screen with the defined settings.

#### Actual behavior

This returns the error: `r360.compositor.setScreen is not a function`

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

The steps required are to initialize a basic repository using the cli. Using any video in static_assets, use the code outlined above from the documentation.

### Solution

The `compositor.setScreen` method needs to be implemented or specified to use something else in the docs.

### Additional Information

* 'react-360' package version: 1.0.0
* 'react-360-web' package version: 1.0.0
* Operating System: MacOS
* Browser: All Browsers

**Comment by tlakomy** [comment]
Can confirm, as of now I don't think it's possible to create a flat screen when using `react-360 init` to create a new project

**Comment by larrylin28** [comment]
We've just released the new update containing all recent added features. Please upgrade your react-360-cli to latest version(1.1.0)

**Comment by drubio1989** [comment]
Hey @larrylin28 thanks for your reply. After upgrading to the latest cli version (1.1.0), I am still unable to play video. I created a blank project with the following code in `client.js`:

    function init(bundle, parent, options = {}) {
        const r360 = new ReactInstance(bundle, parent, {
        fullScreen: true,
         ...options,
      });

      // Render your app content to the default cylinder surface
      r360.renderToSurface(
        r360.createRoot('VideoVR', { /* initial props */ }),
        r360.getDefaultSurface()
      );

      const player = r360.compositor.createVideoPlayer('myplayer');
   
      player.setSource('./static_assets/laptop.mov', '2D');

      r360.compositor.setBackgroundVideo('myplayer');

      r360.compositor.setScreen(
        'default', /* screen name */
        'myplayer', /* player unique id */
        'default', /* surface name */
        0, 0, 600, 400 /* relative position on the surface */
      );
    }

I receive the following error when running `npm start`:
<img width="1121" alt="screen shot 2019-02-19 at 1 28 18 pm" src="https://user-images.githubusercontent.com/6200151/53041714-4ae11500-344a-11e9-8fda-2abfff9e45a1.png">

If any more information  is needed to resolve the issue, let me know. Thanks for helping all of us out with the new release btw.

**Comment by larrylin28** [comment]
Hi, so looks like you are trying to play video from client side, I think you need to pass the video format when playing from client side, e.g. player.setSource('./static_assets/laptop.mp4', '2D', 'mp4')
It's also recommended to play video on react side where work with your other react code. 
I'd recommend you try the "MediaAppTemplate" in the "Sample" folder, which will give you more example on how to play video.

**Comment by drubio1989** [comment]
Thanks @larrylin28, I got it to work now based off the sample directories. Going to close.
